// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhk8Z4rOP-93jNzE7bDX3Qz8UeYcp9-4',
    appId: '1:456461941547:web:9429afdc57451bc93d636e',
    messagingSenderId: '456461941547',
    projectId: 'chat-app-sample-fistkim101',
    authDomain: 'chat-app-sample-fistkim101.firebaseapp.com',
    storageBucket: 'chat-app-sample-fistkim101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuCg_mlQzzXYWiQgJ6IqtTXBKH5LR5eo',
    appId: '1:456461941547:android:5013de09bc3de5d23d636e',
    messagingSenderId: '456461941547',
    projectId: 'chat-app-sample-fistkim101',
    storageBucket: 'chat-app-sample-fistkim101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbH6s-_NVdfuTRrumZbrDggAzq_zaZN-o',
    appId: '1:456461941547:ios:5525ca8eccfde1ef3d636e',
    messagingSenderId: '456461941547',
    projectId: 'chat-app-sample-fistkim101',
    storageBucket: 'chat-app-sample-fistkim101.appspot.com',
    iosClientId: '456461941547-g80f9pqma0jvh1lt6uiufjluno2pv3uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbH6s-_NVdfuTRrumZbrDggAzq_zaZN-o',
    appId: '1:456461941547:ios:5525ca8eccfde1ef3d636e',
    messagingSenderId: '456461941547',
    projectId: 'chat-app-sample-fistkim101',
    storageBucket: 'chat-app-sample-fistkim101.appspot.com',
    iosClientId: '456461941547-g80f9pqma0jvh1lt6uiufjluno2pv3uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
